### ISSUE TITLE
-[SPTNowPlayingInformationUnitViewController titleLabel]: unrecognized selector sent to instance 0x10b279b50

### ISSUE THREAD

**Issue by machineonamission** [iCrazeiOS/Spoticentre#1]
[Sclog.txt](https://github.com/iCrazeiOS/Spoticentre/files/7841097/Sclog.txt)

tweak crashes spotify on load with this error

**Comment by iCrazeiOS** [comment]
Seems like it's caused by the latest Spotify update. I'll take a look at updating the tweak tonight, thanks.

**Comment by iCrazeiOS** [comment]
I've patched the issue and have uploaded it to this GitHub (in packages folder)

Will push patch to Packix now - thanks again for the report

**Comment by machineonamission** [comment]
Now the enhance icon is stretched

![image](https://user-images.githubusercontent.com/35177464/148853402-91813952-020d-41e4-b13a-89888818126a.png)

**Comment by iCrazeiOS** [comment]
ahhh, fantastic...

I've just turned everything off for the night, so will have to take a look at it tomorrow. _hopefully_ shouldn't be too bad to fix

**Comment by iCrazeiOS** [comment]
hey @HexCodeFFF, I've finally had time to fix this issue

fix here: https://github.com/iCrazeiOS/Spoticentre/commit/9d6b0313065da6abdbdc31035abd400ad642fde2

I'm submitting the new deb to Packix now

**Comment by machineonamission** [comment]
sick
