### ISSUE TITLE
Tweak doesn’t work

### ISSUE THREAD

**Issue by machineonamission** [iCrazeiOS/Spoticentre#2]
![73C20AD3-AED1-485B-8AA4-C0E1973A515F](https://user-images.githubusercontent.com/35177464/166878464-1cce21c3-f4f1-480c-81e1-d52b3ed59f50.png)
![D254373E-2929-4FDE-BC1F-2FE0E183B11E](https://user-images.githubusercontent.com/35177464/166878684-e20fa5d6-613b-4941-9582-34511df37e1a.jpeg)
![8093B86F-4905-4383-8CB0-6052E1B2219E](https://user-images.githubusercontent.com/35177464/166878702-09204156-fe63-4011-999f-c31df56abe28.png)

**Comment by iCrazeiOS** [comment]
Yay - Spotify completely broke it again. Will try to update it asap, but I have exams atm

On 5 May 2022, at 08:25, HexCodeFFF ***@***.***> wrote:

﻿

[73C20AD3-AED1-485B-8AA4-C0E1973A515F]<https://user-images.githubusercontent.com/35177464/166878464-1cce21c3-f4f1-480c-81e1-d52b3ed59f50.png>
[D254373E-2929-4FDE-BC1F-2FE0E183B11E]<https://user-images.githubusercontent.com/35177464/166878684-e20fa5d6-613b-4941-9582-34511df37e1a.jpeg>
[8093B86F-4905-4383-8CB0-6052E1B2219E]<https://user-images.githubusercontent.com/35177464/166878702-09204156-fe63-4011-999f-c31df56abe28.png>

**Comment by machineonamission** [comment]
No pressure at all, just letting you know

**Comment by iCrazeiOS** [comment]
Fixed in v2.,2
