### ISSUE TITLE
Doesn’t work on the latest version

### ISSUE THREAD

**Issue by JackPlaysGames0510** [iCrazeiOS/Spoticentre#3]
Can you make this work on 8.8.46 and up

**Comment by iCrazeiOS** [comment]
works on 8.8.48.499. are you using the version from my repo? (3.0)

**Comment by iCrazeiOS** [comment]
hmm, after a few app launches, I just got an updated app design.
Will try to update it now

**Comment by JackPlaysGames0510** [comment]
Ok sounds good

**Comment by iCrazeiOS** [comment]
Do you know if they have scrapped the new UI? I don't really use Spotify anymore

**Comment by JackPlaysGames0510** [comment]
I think they have removed the new ui because it started working again randomly again
