### ISSUE TITLE
Can you fix this

### ISSUE THREAD

**Issue by JackPlaysGames0510** [iCrazeiOS/Spoticentre#4]
![IMG_0662](https://github.com/iCrazeiOS/Spoticentre/assets/48178959/45122a68-ad4a-45c3-b5ac-5a717d0ab42c)
This happens when you turn on smart shuffle

**Comment by iCrazeiOS** [comment]
Thanks, will look into this when I'm free

**Comment by JackPlaysGames0510** [comment]
ok sounds good man

**Comment by iCrazeiOS** [comment]
Should be fixed. Uploading to my repo now

**Comment by JackPlaysGames0510** [comment]
Ok thanks

**Comment by JackPlaysGames0510** [comment]
It’s perfect thanks

**Comment by iCrazeiOS** [comment]
Great
