### ISSUE TITLE
It stop working

### ISSUE THREAD

**Issue by JackPlaysGames0510** [iCrazeiOS/Spoticentre#5]
![IMG_0668](https://github.com/iCrazeiOS/Spoticentre/assets/48178959/7a2c297d-9e5b-418b-b1ef-bbb6c1e5e625)

**Comment by iCrazeiOS** [comment]
Is this caused by an app update?

**Comment by iCrazeiOS** [comment]
Managed to enable the A/B test for the refactored UI

Got the tweak mostly working at this point

**Comment by iCrazeiOS** [comment]
Uploading to repo now, let me know if it works for you

**Comment by JackPlaysGames0510** [comment]
They must of just updated the ui

**Comment by JackPlaysGames0510** [comment]
The app it self didn’t update

**Comment by JackPlaysGames0510** [comment]
Works great thanks man

**Comment by iCrazeiOS** [comment]
Awesome
